"""add is_verified column to users

Revision ID: 03aa6a7246cc
Revises: 464931de79c3
Create Date: 2026-05-11 13:26:05.115264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03aa6a7246cc'
down_revision: Union[str, Sequence[str], None] = '464931de79c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
