"""add payment_method_id to users

Revision ID: 3016a3a36064
Revises: 03aa6a7246cc
Create Date: 2026-05-11 21:02:30.666424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3016a3a36064'
down_revision: Union[str, Sequence[str], None] = '03aa6a7246cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_id')
    # ### end Alembic commands ###
