"""add new column pickup_lat, pickup_lon, dropoff_lat, dropoff_lon, price to table Trip

Revision ID: 4a613485f933
Revises: 4e1214b4482e
Create Date: 2026-05-04 18:44:23.959914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a613485f933'
down_revision: Union[str, Sequence[str], None] = '4e1214b4482e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('pickup_lat', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('pickup_lon', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('dropoff_lat', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('dropoff_lon', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'price')
    op.drop_column('trips', 'dropoff_lon')
    op.drop_column('trips', 'dropoff_lat')
    op.drop_column('trips', 'pickup_lon')
    op.drop_column('trips', 'pickup_lat')
    # ### end Alembic commands ###
